{"uuid": "897e0b88-1d29-45dd-84bf-89640c9edc2e", "children": ["9aebe370-cafa-4637-9f6c-4dab4d43ff17"], "befores": [{"name": "_xunit_setup_class_fixture_TestAddMember", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pycharm\\Selenium\\testcase\\test_add_member.py\", line 12, in setup_class\n    self.home = LoginPage().login()\n  File \"D:\\pycharm\\Selenium\\page\\base.py\", line 21, in __init__\n    self.driver = webdriver.Remote(command_executor='http://192.168.254.128:5444/wd/hub', capabilities=capabilities)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 428, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 347, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 369, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 714, in urlopen\n    httplib_response = self._make_request(\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 466, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 461, in _make_request\n    httplib_response = conn.getresponse()\n  File \"D:\\python\\Python39\\lib\\http\\client.py\", line 1377, in getresponse\n    response.begin()\n  File \"D:\\python\\Python39\\lib\\http\\client.py\", line 320, in begin\n    version, status, reason = self._read_status()\n  File \"D:\\python\\Python39\\lib\\http\\client.py\", line 281, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"D:\\python\\Python39\\lib\\socket.py\", line 704, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1690513028185, "stop": 1690513328301}], "start": 1690513028185, "stop": 1690513328842}